### ISSUE TITLE
中文书名征集

### ISSUE THREAD

**Issue by SangKa** [SangKa/PWA-Book-CN#12]
英文书名为《Progressive Web Apps》
我个人想将中文书命名为《PWA 实战》，原书名虽然没有 `in Action` 字样，但实战系列一直是Manning的标志
编辑建议使用《PWA实战：面向下一代的Progressive Web Apps》，保留原书书名的同时提升全称关键字的搜索命中率

现需要大家的智慧，提供一个能让大家满意的中文名

**Comment by WhiteYin** [comment]
编辑起的名字很好，我投一票~~

**Comment by SangKa** [comment]
@WhiteYin 谢谢你的宝贵意见

**Comment by SeeSayAndSun** [comment]
对于我这种小白来说我感觉这个名字不够吸引眼球，最好是能有个博人眼球的名字。毕竟就算内容再好，名字不吸引人的话也不会去理解的你的内容。（纯属个人看法）

**Comment by cyan33** [comment]
《PWA实战：开发渐进式Web应用》

**Comment by SangKa** [comment]
@thomasyimgit 谢谢你的宝贵意见

**Comment by parrotdance** [comment]
个人比较赞成 @thomasyimgit 的意见:《PWA实战：开发渐进式Web应用》
不知道将"Web"改为"网络"如何? 如:《PWA实战：开发渐进式网络应用》
对于像我一样半吊子水平的读者来说, 也许英文缩写 ---- PWA, 或全中文名词 ---- 渐进式网络应用, 命中率会高一些

**Comment by SangKa** [comment]
@parrotdance 谢谢你的宝贵意见 十分中肯

**Comment by Lizhooh** [comment]
《PWA 从入门到精通》

**Comment by hrpc** [comment]
缩写和全称都保留《PWA实战：面向下一代的Progressive Web Apps》 + 1

**Comment by SangKa** [comment]
@Lizhooh 谢谢你的宝贵意见 个人觉得 Manning 系统的书不适合翻译成《xx 从入门到精通》

**Comment by SangKa** [comment]
@hrpc 谢谢你的宝贵意见 编辑又找到知音了 :smile_cat:

**Comment by zanjs** [comment]
《PWA实战：下一代渐进式Web应用》

**Comment by buwenzheng** [comment]
必须编辑的那个名字 《PWA实战：面向下一代的Progressive Web Apps》，缩写和全称都有

**Comment by SangKa** [comment]
@buwenzheng 谢谢你的宝贵意见

**Comment by zwwill** [comment]
《了不起的PWA》

**Comment by SangKa** [comment]
@zwwill 谢谢你的宝贵意见

**Comment by cody1991** [comment]
《PWA实战：下一代渐进式Web应用》 + 1

gitbooks看的差不多了 很不错的一本书 期待上线

**Comment by SangKa** [comment]
@cody1991 谢谢你的宝贵意见 也感谢你的支持

**Comment by wangmingquan** [comment]
《PWA小书》

**Comment by JerryMissTom** [comment]
我也支持编辑的，搜索方便

**Comment by SangKa** [comment]
@wangmingquan 谢谢你的宝贵意见

**Comment by SangKa** [comment]
@JerryMissTom 谢谢你的宝贵意见

**Comment by kaindy7633** [comment]
PWA和Progressive Web Apps 这两个关键词建议保留，至于其他的看楼主喜好

**Comment by SangKa** [comment]
@kaindy7633 谢谢你的宝贵意见

**Comment by yanfeng12** [comment]
现在名字定下来了吗？或者有预售链接吗？
在淘宝或者京东搜索pwa都是一些工业用品或者螺丝，书名最好有全称。
《PWA实战：面向下一代的Progressive Web Apps》这个还可以吧。

**Comment by SangKa** [comment]
@yanfeng12 谢谢你的宝贵意见
名字还没最后确定 但应该就会用你选的这个名字
预售链接的话出来的话 我会第一时间同步给大家 大概就下个月

**Comment by ronffy** [comment]
《深入PWA：面向下一代的Progressive Web Apps》
期待新书出版，迫不及待了 ⛽️⛽️

**Comment by SangKa** [comment]
@wanghairong-i 谢谢你的宝贵意见与支持

**Comment by ChinaCarlos** [comment]
《PWA成神之路》

**Comment by SangKa** [comment]
@maliaoMJ 谢谢你的宝贵意见 这个书名太超脱了

**Comment by SangKa** [comment]
谢谢各位的集思广益，现在书名已定，最后选用的还是大家赞同比较多的 《PWA实战：面向下一代的Progressive Web App》。
再次感谢各位。

**Comment by Lizhooh** [comment]
《PWA 权威指南》

**Comment by SangKa** [comment]
@Lizhooh 虽然书名已经定了 但还是谢谢你的宝贵意见
