### ISSUE TITLE
第6章的代码是不是不完整？

### ISSUE THREAD

**Issue by amplee** [SangKa/PWA-Book-CN#15]
我在代码清单里下载下来，怎么都跑不起来。看了好几遍文章，我还是不太明白，除了一开始那个欢迎的推送能正常跑起来，后面的推送都无法触发，我尝试给每个文章的a标签加了click事件，再发送对应的/sendMessage请求，还是不能推送。到底是哪里出了问题，望解答~

**Comment by SangKa** [comment]
![image](https://user-images.githubusercontent.com/6177271/33556261-39ccbcb4-d93e-11e7-81e7-3e1a17ba3f59.png)

需要订阅时的用户详情，而示例中的 `/sendMessage` 接口需要手动传入这些参数，代码如下:

https://github.com/deanhume/progressive-web-apps-book/blob/05c5f67bd11829491f7e012ec689085fe55434e9/chapter-6/push-notifications/server.js#L35-L47

**Comment by amplee** [comment]
谢大神回复，但这段代码我有加的，还是不能触发/sendMessage，而且我看了下，/register的参数跟他的是一样的吧？假如我把这index.html的/register请求改成/sendMessage，在页面首次打开的并点击允许接受通知就能显示/sendMessage的推送内容了，但是后面不能再触发任何推送了，是我描述的不清楚吗？

**Comment by amplee** [comment]
订阅时的用户详情，是一定要保存到数据库才能用吗？首次推送的时候不是获取了用户的订阅详情吗？我调了断点，首次发起的请求（不管是/sendMessage还是/register）能进去，后面怎么点击页面都进不去这两个推送了。

**Comment by amplee** [comment]
我迷惑的点是，如何第二次触发这个推送，就比如怎么才能再次触发/sendMessage这个推送服务？

**Comment by SangKa** [comment]
需要改造下代码，前端改也行，后端改也行，目的就是要把注册成功后的那几个重要参数保存好，然后让后端发推送通知时可以正常使用这些参数。`/register`  好用就是因为它已经把这些参数准备好了。
不知道这样说你能明白嘛

**Comment by amplee** [comment]
我先把参数保存下来试一下，谢谢！
所以这个是因为参数信息的缺失造成的？像/register的推送是因为在index.html里发出了这个请求才发起的推送，那是在什么情况下触发了/sendMessage这个推送呢？浏览器自己触发的？过多长时间会触发呢？

**Comment by SangKa** [comment]
我看了下，代码里并没有触发 `/sendMessage` 接口的操作，建议后端保存参数，前端正常发 `/sendMessage` 请求即可

**Comment by amplee** [comment]
好的，我先试一下，谢谢耐心解答~！
