### ISSUE TITLE
添加到主屏幕如何取消？多个浏览器都添加会怎样？

### ISSUE THREAD

**Issue by amplee** [SangKa/PWA-Book-CN#17]
添加到主屏幕后，提示成功，但是主屏幕并没有找到，如何再次触发这个事件？我卸载了chrome浏览器重装，还是没有触发。
假如是多个浏览器添加的话，会发生什么呢？

**Comment by amplee** [comment]
我发现只是添加到浏览器的主屏幕，并没有添加到手机的主屏幕

**Comment by SangKa** [comment]
没添加成功，首先试试安卓自带浏览器或者翻墙后用 Chrome
再次触发 Chrome 有添加到主屏幕这个选项，也可以参照代码清单5.9
至于多个浏览器添加会是什么情况，我也不清楚，没实际操作过

**Comment by JerryMissTom** [comment]
我使用魅族手机试了下，先使用自带的浏览器添加百度至手机主屏幕，然后使用Chrome重复此操作，使用同样的名字，发现桌面只有一个图标。我接着使用Chrome添加百度但是填写不同的名字，则会出现多个图标。使用魅族手机自带的浏览器添加百度使用不同的名字，也会出现多个图标。
