### ISSUE TITLE
3.2节的" bit.ly/chapter-pwa-3"链接有问题

### ISSUE THREAD

**Issue by FengHaiSheng** [SangKa/PWA-Book-CN#2]
如题

**Comment by SangKa** [comment]
感谢纠错 
看了下 书中给的短连接都失效了 后面我会换成重新生成的短连接
第三章的示例地址可以点击[这里](https://github.com/deanhume/progressive-web-apps-book/tree/master/chapter-3)查看

另外 [README](https://github.com/SangKa/PWA-Book-CN#本书相关资源) 中也有书中代码链接
