### ISSUE TITLE
因为墙的原因 web push 在国内好像chrome上无法使用。

### ISSUE THREAD

**Issue by qxkxzw** [SangKa/PWA-Book-CN#29]
第六章的代码总是报连接错误，查了一下web push的原理。推送数据是要发给浏览器厂商的服务器，再转发给用户的，而国内屏蔽了谷歌的服务，所以实际上市场占有量最大的chrome无法使用这项功能。

如果仅仅是对火狐和Safari的话确实不太实用。书中是否应该对此有所提及，避免其他要支持chrome的开发者浪费时间？

**Comment by SangKa** [comment]
Chrome 用了 [FCM](https://firebase.google.com/docs/cloud-messaging/?hl=zh-cn)，这个国内是被墙的。
原书的作者肯定对国内这种被墙现象是无感的。
