### ISSUE TITLE
第七章在线版

### ISSUE THREAD

**Issue by yesvods** [SangKa/PWA-Book-CN#33]
第七章之后，是否已经翻译完毕了呢，有没有开放在线阅读的计划？谢谢。

**Comment by SangKa** [comment]
README 上其实有写
如果想阅读后面六章的话，纸质书即将出版，开发在线阅读计划暂时没有。

**Comment by xrr2016** [comment]
期待纸质版

**Comment by SangKa** [comment]
@xrr2016 快了快了 🤓
