### ISSUE TITLE
楼主不考虑侵权问题？

### ISSUE THREAD

**Issue by andycall** [SangKa/PWA-Book-CN#7]
https://www.zhihu.com/question/21717704

**Comment by SangKa** [comment]
有考虑过，这样在没有任何授权的情况下以个人形式发布肯定是涉及侵权了，
同样的问题其实我之前也问过 ([点击查看](https://github.com/RxJS-CN/RxJS-Docs-CN/issues/75))，但我是这样考虑的：
首先无论是出版社出书，还是像我这种，其目的都是为了传播知识，只是区别在于前者是商业行为，在传播知识的同时以营利为目的。
我的出发点很简单，为了让国内开发者第一时间能接触到 PWA 这项技术。
至于版权问题，起初我是想出版此书的，但最后没能找到中文版权归属。后面如果版权方通知我侵权了，我会积极配合版权方，如果涉及到法律纠纷，我会自行承担。

**Comment by andycall** [comment]
为楼主这样的精神打call

**Comment by SangKa** [comment]
@andycall 谢谢！
其实有很多好书，国内翻译完出版都已经2年之后了。这也是触动我的一个点。

**Comment by whatwg6** [comment]
m

**Comment by SangKa** [comment]
目前经人介绍 已经联系到有中文翻译版权的出版社 后续可能会以出版的形式和大家见面
